### ISSUE TITLE
dead link (Google Billion Word Dataset for Torch)

### ISSUE THREAD

**Issue by jxmorris12** [rdspring1/PyTorch_LM#11]
Hi, I'd like to use your language model for my research. I can't train it because the link to the `Google Billion Word Dataset for Torch` is down. Is there a mirror somewhere?

**Comment by rdspring1** [comment]
You can try using the original data - [1 Billion Word Dataset ](http://www.statmt.org/lm-benchmark/1-billion-word-language-modeling-benchmark-r13output.tar.gz)
