### ISSUE TITLE
Is the dataset offline?

### ISSUE THREAD

**Issue by CeadeS** [rdspring1/PyTorch_LM#12]
Dataset seems to be offline. Is it possible to reup it again?

**Comment by rdspring1** [comment]
Both versions or just the Torch preprocessed dataset.

**Comment by CeadeS** [comment]
this link? http://lisaweb.iro.umontreal.ca/transfert/lisa/users/leonardn/billionwords.tar.gz

**Comment by rdspring1** [comment]
I download the original dataset from [here]( https://www.statmt.org/lm-benchmark/1-billion-word-language-modeling-benchmark-r13output.tar.gz).
