### ISSUE TITLE
Nondeterministic result?

### ISSUE THREAD

**Issue by eric-haibin-lin** [rdspring1/PyTorch_LM#3]
Hi, I was trying to run your example, but the result is non-deterministic each time (even if I set dropout=0.0). Is that expected?
(BTW, I'm using GBWStream to read the dataset with `deterministic=True`, I can post the code if you want to take a look)

**Comment by rdspring1** [comment]
I haven't been using GBWStream in my experiments. It is slower than FastGBW, which loads the entire dataset in memory.

If the **deterministic** setting is True, then the sentences are not shuffled. However, the parameters of the network are randomly initialized, so you could still get non-deterministic results.

What kind of behavior did you want to see?
