### ISSUE TITLE
ImportError: cannot import name 'LogUniformSampler'

### ISSUE THREAD

**Issue by songyuzhou324** [rdspring1/PyTorch_LM#5]
After running: 'python3 setup.py build_ext --inplace', I still got ImportError: cannot import name 'LogUniformSampler'. It seems that log_uniform module is not built correctly.

Any suggestion?

Thanks!

**Comment by rdspring1** [comment]
Did you add the log_uniform folder to your PYTHONPATH?

**Comment by songyuzhou324** [comment]
Thanks for your reply! I have added log_uniform folder to my PYTHONPATH.

Another question is, if I have a folder named 'data' contains my own data, instead of downloading GBW data. What's the easiest way to run the code on my own data?

**Comment by rdspring1** [comment]
You would need to build a custom Dataset / Dataloader class for your dataset, that outputs inputs and labels for the language model task.

**Comment by miumiuUncle** [comment]
> 

How did you solve this problem？thanks
