### ISSUE TITLE
Pretrained Model?

### ISSUE THREAD

**Issue by allenanie** [rdspring1/PyTorch_LM#7]
Nice work! It's so tragic that when I type "pytorch language models", this is not the first repo that shows up! 

Do you plan to release the pre-trained model? 

(I see it takes roughly 3 days...so probably it's ok)

**Comment by rdspring1** [comment]
Thanks! I was thinking about adding Multi-GPU support to reduce the training time. Maybe I will release a pre-trained model then.

**Comment by GaryYufei** [comment]
Hi, I am really happy if there is pre-trained model!!
