### ISSUE TITLE
Preprocess problem

### ISSUE THREAD

**Issue by jiangtianli91** [rdspring1/PyTorch_LM#8]
It seems torch.load() cannot load train_data.th7? 
I cannot figure out how to "run "process_gbw.py" on the "train_data.th7" file to create the "train_data.sid" file."

**Comment by rdspring1** [comment]
PyTorch does not support Torch tensors anymore. If you install PyTorch 0.4, you can convert the Torch tensors into the PyTorch format. torch.load() is only for PyTorch tensors.
