### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by Machine-Tom** [rdspring1/PyTorch_LM#9]
File "main_dev.py", line 99, in repackage_hidden
    return [repackage_hidden(state) for state in h]
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 381, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

Have you met this kind of question before?

**Comment by rdspring1** [comment]
Did you print the shape of the h variable? It is a recursive function, so there might be a corner case that needs to be fixed. You get this error when h is an empty tensor.
